[package]
name = "klockan"
version = "0.1.0"
authors = ["Daniel Lublin <daniel@lublin.se>"]

[dependencies]
rppal = "0.11"
chrono = "0.4"
ctrlc = { version = "3.0", features = ["termination"] }
structopt = "0.2.18"
